// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddOnCard: typeof import('./src/components/AddOnCard.vue')['default']
    CardInput: typeof import('./src/components/CardInput.vue')['default']
    NavMain: typeof import('./src/components/NavMain.vue')['default']
    NavNumber: typeof import('./src/components/NavNumber.vue')['default']
    NavStep: typeof import('./src/components/NavStep.vue')['default']
    NavText: typeof import('./src/components/NavText.vue')['default']
    PageAddOn: typeof import('./src/components/PageAddOn.vue')['default']
    PageCheckout: typeof import('./src/components/PageCheckout.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PageInfo: typeof import('./src/components/PageInfo.vue')['default']
    PageMain: typeof import('./src/components/PageMain.vue')['default']
    PagePlan: typeof import('./src/components/PagePlan.vue')['default']
    PageSummary: typeof import('./src/components/PageSummary.vue')['default']
    PlanCard: typeof import('./src/components/PlanCard.vue')['default']
    RmInput: typeof import('./src/components/RmInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
